# Generated by Django 5.2.1 on 2025-05-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='adjuntos/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fecha_esperada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='prioridad',
            field=models.CharField(blank=True, choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], max_length=10),
        ),
    ]
